# what language the app is built on
language: python

# what version to use
python:
  - 3.7
  - 3.6

# what branches to test
branches:
  only:
    - master

# setup environment
install:
  - pip install coverage
  - pip install coveralls
  - pip install flake8
  - pip install -r requirements.txt

# run before testing unit tests
before_script:
  - 'flake8 PlanIt'

# run the unit tests
script:
  - python coverage run -m unittest discover

# generate coverage report
after_success:
  - coverage report
  - coveralls
