import pandas as pd
import numpy as np

def get_solar_data(station_id):
    '''
    This function takes the solar station id as an input and inputs the
    corresponding data files.
    '''

    def solar_energy(panel_area, efficiency, radiation, performance_ratio):
    '''
    This function takes solar panel parameters and solar radiation data as
    inputs and returns the energy generated in Watts

    Inputs
        panel_area = solar panel area
        efficiency = solar panel efficiency
        radiation = solar irradiance in W/m^2
        performance ratio = performance ratio of solar panel

    Outputs
        energy = Amount of energy generated by solar panel
    '''
    energy = panel_area * efficiency * radiation * performance_ratio

    return energy
